# Generated by Django 5.2.7 on 2025-11-02 14:05

import accounts.models.profile_model
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='Valid Iranian mobile number (09xxxxxxxxx or +989xxxxxxxxx).', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid Iranian phone number (e.g. 09123456789 or +989123456789).', regex='^(?:\\+?98|0)?9\\d{9}$')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('banned', 'Banned'), ('deleted', 'Deleted'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('doctor', 'Doctor'), ('physiotherapist', 'Physiotherapist'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('patient', 'Patient'), ('manager', 'Manager'), ('assistant', 'Assistant'), ('accountant', 'Accountant'), ('lab_technician', 'Laboratory Technician'), ('radiologist', 'Radiologist'), ('imaging_tech', 'Medical Imaging Technician'), ('pharmacist', 'Pharmacist'), ('cleaner', 'Cleaner'), ('security', 'Security')], db_index=True, default='user', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, upload_to=accounts.models.profile_model.profile_avatar_upload_to)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian')], default='fa', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Setting',
                'verbose_name_plural': 'User Settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
