# Generated by Django 5.2.7 on 2025-11-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='national_code',
            field=models.CharField(blank=True, help_text='National code', max_length=10, null=True),
        ),
    ]
