# Generated by Django 5.2.7 on 2025-11-07 12:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profilemodel_national_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medical_license_number', models.CharField(help_text='Medical council registration number', max_length=50, unique=True)),
                ('bio', models.TextField(blank=True, help_text='Professional biography and qualifications')),
                ('years_of_experience', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_consultation_duration', models.PositiveIntegerField(default=30, help_text='Default consultation duration in minutes')),
                ('default_price_irr', models.DecimalField(decimal_places=0, help_text='Default consultation price in Iranian Rial', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_accepting_patients', models.BooleanField(default=True, help_text='Whether the doctor is currently accepting new appointments')),
                ('is_verified', models.BooleanField(default=False, help_text='Admin verification status')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('specializations', models.ManyToManyField(blank=True, related_name='doctors', to='accounts.specializationmodel')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_accepting_patients', 'is_verified'], name='accounts_do_is_acce_1a1883_idx')],
            },
        ),
    ]
