# Generated by Django 5.2.7 on 2025-11-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_specializationmodel_doctormodel'),
        ('clinic', '0002_alter_availabilityexceptionmodel_doctor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorModel',
            new_name='DoctorProfileModel',
        ),
        migrations.RenameIndex(
            model_name='doctorprofilemodel',
            new_name='accounts_do_is_acce_096ec8_idx',
            old_name='accounts_do_is_acce_1a1883_idx',
        ),
    ]
