# Generated by Django 5.2.7 on 2025-11-07 13:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_doctormodel_doctorprofilemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofilemodel',
            name='default_price_irr',
            field=models.DecimalField(decimal_places=0, default=Decimal('100000'), max_digits=21, validators=[django.core.validators.MinValueValidator(100000)]),
        ),
    ]
