# Generated by Django 5.2.7 on 2025-11-02 16:46

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='Valid Iranian mobile number (09xxxxxxxxx or +989xxxxxxxxx).', max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid Iranian phone number (e.g. 09123456789 or +989123456789).', regex='^(?:\\+?98|0)?9\\d{9}$')])),
                ('type', models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('reset_password', 'Reset Password')], default='login', max_length=32)),
                ('salt', models.CharField(max_length=32)),
                ('code_hash', models.CharField(max_length=64)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'indexes': [models.Index(fields=['phone_number', '-created_at'], name='authenticat_phone_n_0af7d0_idx')],
            },
        ),
    ]
