# Generated by Django 5.2.7 on 2025-11-07 12:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityExceptionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('exception_type', models.CharField(choices=[('unavailable', 'Unavailable (blocks recurring)'), ('available', 'Available (adds new slots)')], max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('price_irr', models.DecimalField(blank=True, decimal_places=0, help_text='Price in Iranian Rial', max_digits=21, null=True, validators=[django.core.validators.MinValueValidator(100000)])),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Appointment slot duration in minutes', null=True)),
                ('appointment_type', models.CharField(blank=True, choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency')], max_length=20, null=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for exception (e.g., vacation, conference)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Availability Exception',
                'verbose_name_plural': 'Availability Exceptions',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['doctor', 'date'], name='clinic_avai_doctor__003a0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecurringAvailabilityModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price_irr', models.DecimalField(decimal_places=0, help_text='Price in Iranian Rial', max_digits=21, validators=[django.core.validators.MinValueValidator(100000)])),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Appointment slot duration in minutes')),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency')], default='consultation', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this availability is currently active')),
                ('valid_from', models.DateField(default=django.utils.timezone.now, help_text='When this availability pattern becomes active')),
                ('valid_until', models.DateField(blank=True, help_text='When this availability pattern expires (null = no expiry)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Availability',
                'verbose_name_plural': 'Recurring Availabilities',
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['doctor', 'is_active', 'day_of_week'], name='clinic_recu_doctor__ef1098_idx')],
                'unique_together': {('doctor', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
