# Generated by Django 5.2.7 on 2025-11-07 12:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_specializationmodel_doctormodel'),
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityexceptionmodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='accounts.doctormodel'),
        ),
        migrations.AlterField(
            model_name='recurringavailabilitymodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_availabilities', to='accounts.doctormodel'),
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency')], default='consultation', max_length=20)),
                ('price_irr', models.DecimalField(decimal_places=0, help_text='Final agreed price in Iranian Rial', max_digits=21, validators=[django.core.validators.MinValueValidator(100000)])),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20)),
                ('patient_notes', models.TextField(blank=True, help_text='Notes from patient about symptoms/concerns')),
                ('doctor_notes', models.TextField(blank=True, help_text='Internal notes from doctor')),
                ('cancellation_reason', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='accounts.doctormodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-appointment_date', '-start_time'],
                'indexes': [models.Index(fields=['doctor', 'appointment_date', 'status'], name='clinic_appo_doctor__8ead60_idx'), models.Index(fields=['patient', 'appointment_date', 'status'], name='clinic_appo_patient_9aa678_idx'), models.Index(fields=['appointment_date', 'start_time', 'end_time'], name='clinic_appo_appoint_4136ae_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='appointment_start_before_end')],
            },
        ),
    ]
