# Generated by Django 5.2.7 on 2025-11-04 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField(help_text='Payment amount in the smallest currency unit (Rial/Toman)')),
                ('currency', models.CharField(choices=[('IRR', 'Rial'), ('IRT', 'Toman')], default='IRR', help_text='Currency of the transaction', max_length=3)),
                ('description', models.TextField(help_text='Description of the transaction')),
                ('authority', models.CharField(help_text='Unique authority code from Zarinpal', max_length=36, unique=True)),
                ('ref_id', models.CharField(blank=True, help_text='Reference ID from successful payment verification', max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current status of the transaction', max_length=20)),
                ('card_pan', models.CharField(blank=True, help_text='Masked card number used for payment', max_length=19, null=True)),
                ('fee', models.PositiveIntegerField(default=0, help_text='Transaction fee charged by Zarinpal')),
                ('mobile', models.CharField(blank=True, help_text="User's mobile number", max_length=15, null=True)),
                ('email', models.EmailField(blank=True, help_text="User's email address", max_length=254, null=True)),
                ('callback_url', models.URLField(help_text='URL to redirect user after payment completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who made the payment', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='finance_tra_user_id_e70fa4_idx'), models.Index(fields=['authority'], name='finance_tra_authori_d378b1_idx'), models.Index(fields=['created_at'], name='finance_tra_created_6296bb_idx')],
            },
        ),
    ]
