# Generated by Django 5.2.7 on 2025-11-07 12:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_availabilityexceptionmodel_doctor_and_more'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_irr', models.DecimalField(decimal_places=0, help_text='Payment amount in Iranian Rial', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('provider', models.CharField(choices=[('Zarinpal', 'Zarinpal')], default='Zarinpal', max_length=20)),
                ('provider_payment_id', models.CharField(blank=True, help_text='Payment ID from payment provider (e.g., Stripe PaymentIntent ID)', max_length=255, null=True, unique=True)),
                ('provider_charge_id', models.CharField(blank=True, help_text='Charge ID from payment provider', max_length=255)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique key for idempotent payment processing', max_length=255, unique=True)),
                ('payment_method_last4', models.CharField(blank=True, help_text='Last 4 digits of payment method (for display only)', max_length=4)),
                ('payment_method_brand', models.CharField(blank=True, help_text='Payment method brand (e.g., Visa, Mastercard)', max_length=20)),
                ('refunded_amount_irr', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Total refunded amount in Iranian Rial', max_digits=21, validators=[django.core.validators.MinValueValidator(0)])),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for payment failure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='clinic.appointmentmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_irr', models.DecimalField(decimal_places=0, help_text='Refund amount in Iranian Rial', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField(help_text='Reason for refund')),
                ('provider_refund_id', models.CharField(blank=True, help_text='Refund ID from payment provider', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(help_text='Admin who initiated the refund', on_delete=django.db.models.deletion.PROTECT, related_name='refunds_created', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.paymentmodel')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEventModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('Zarinpal', 'Zarinpal')], max_length=20)),
                ('provider_event_id', models.CharField(db_index=True, help_text='Unique event ID from payment provider', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='Event type (e.g., payment_intent.succeeded)', max_length=100)),
                ('processed', models.BooleanField(db_index=True, default=False, help_text='Whether this event has been processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(help_text='Full webhook payload for debugging')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of processing attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'processed'], name='finance_web_provide_7582ae_idx'), models.Index(fields=['event_type', 'processed'], name='finance_web_event_t_eaea81_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['user', 'status'], name='finance_pay_user_id_8b2c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['appointment', 'status'], name='finance_pay_appoint_eb1707_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['provider_payment_id'], name='finance_pay_provide_9e3b87_idx'),
        ),
        migrations.AddIndex(
            model_name='refundmodel',
            index=models.Index(fields=['payment', 'status'], name='finance_ref_payment_40e6e9_idx'),
        ),
    ]
