# Generated by Django 5.2.7 on 2025-11-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(db_index=True, max_length=260, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(db_index=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(db_index=True, max_length=140, unique=True),
        ),
    ]
